/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Objetos.Equipo;
import Objetos.Jugador;
import XML.XML;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;
import java.util.TreeSet;

/**
 *
 * @author Alumno
 */
public class InterfazConsulta extends javax.swing.JFrame {

    XML conexion;

    /**
     * Creates new form InterfazConsulta
     */
    public InterfazConsulta(XML conexion) {
        this.conexion=conexion;
        initComponents();
        cargarArea();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void cargarArea() {
        ArrayList<Equipo> array = new ArrayList<Equipo>();
        array = conexion.consultaEquipos();
        getjTextArea1().append("Equipos\n");
        for (int i = 0; i < array.size(); i++) {
            getjTextArea1().append("    Equipo\n");
            getjTextArea1().append("        " + array.get(i).getNombre() + "\n");
            getjTextArea1().append("        " + String.valueOf(array.get(i).getFundacion()) + "\n");
            if (array.get(i).getJugadores().size() == 0) {
                getjTextArea1().append("        No tiene Jugadores\n");
            } else {
                getjTextArea1().append("        Jugadores\n");
                Set<Jugador> arrayJugadores = new TreeSet<Jugador>();
                arrayJugadores = array.get(i).getJugadores();
                Iterator<Jugador> jugadores = arrayJugadores.iterator();
                while (jugadores.hasNext()) {
                    Jugador j = jugadores.next();
                    jTextArea1.append("            "+j.getNombre()+"\n");
                    jTextArea1.append("            "+String.valueOf(j.getEdad())+"\n");
                    jTextArea1.append("            "+j.getPosicion()+"\n");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("Base XML");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextArea1
     */
    public javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }
}
